apiVersion: v1
kind: ConfigMap
metadata:
  name: feeder-config
  namespace: waziup
data:
  default.yaml: |
    endpoint:
      id: tb1
      url: http://feeder
    
    elasticsearch:
      host: elasticsearch
      port: 9200
    
    orion:
      # MUST NOT end with slash
      uri: http://orion:1026
    
    tasks:
    - trigger: subscription
      orion:
        service: watersense
        servicePath: /FARM2/TESTS
      elasticsearch:
        index: farm2
      filter:
        attributes:
        - SM1
        - SM2
    - trigger: subscription
      orion:
        service: watersense
        servicePath: /FARM1/TESTS
      elasticsearch:
        index: farm1
      filter:
        attributes:
        - SM1
        - SM2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: waziup
  name: feeder
spec:
  replicas: 1
  template:
    metadata:
      name: feeder
      labels:
        app: feeder
    spec:
      containers:
      - name: feeder
        image: waziup/feeder
        env:
        - name: FEEDER_EXTRA_CONFIG_DIR
          value: /etc/feeder
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /etc/feeder
          name: feeder-config
      volumes:
      - name: feeder-config
        configMap:
          name: feeder-config
          items:
          - key: default.yaml
            path: default.yaml

---

apiVersion: v1
kind: Service
metadata:
  namespace: waziup
  labels:
    name: feeder
  name: feeder
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: feeder
