# Defines the environment variables from docker-compose
endpoint:
  port: SERVER_PORT
  url: FEEDER_NAME

elasticsearch:
  uri: ELASTICSEARCH_URL
  elsPrefix: ELASTICSEARCH_PREFIX

orion:
  uri: ORION_URL
